name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  dockerhubUsername: ${{ secrets.DOCKERHUB_USERNAME }}
  dockerhubToken: ${{ secrets.DOCKERHUB_TOKEN }}
  dockerhubPassword: ${{ secrets.DOCKERHUB_PASSWORD }}
  githubRepo: cyxou/firefly-iii-telegram-bot
  FORCE_COLOR: 1

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Put back the git branch into git (Earthly uses it for tagging)
        run: |
          branch=""
          if [ -n "$GITHUB_HEAD_REF" ]; then
            branch="$GITHUB_HEAD_REF"
          else
            branch="${GITHUB_REF##*/}"
          fi
          git checkout -b "$branch" || true

      - name: Download latest earthly
        run: "sudo /bin/sh -c 'wget https://github.com/earthly/earthly/releases/download/v0.5.23/earthly-linux-amd64 -O /usr/local/bin/earthly && chmod +x /usr/local/bin/earthly'"

      - name: Earthly version
        run: earthly --version

  # push_docker_image:
  #   needs: build_and_test
  #   runs-on: ubuntu-latest
  #   steps:

      - name: Docker Login
        run: docker login --username "$dockerhubUsername" --password "$dockerhubToken"

      - name: Push docker image
        run: earthly --build-arg DOCKERHUB_REPO=$githubRepo --push +image

      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ env.dockerhubUsername }}
          password: ${{ env.dockerhubPassword }}
          repository: ${{ env.githubRepo }}
          short-description: ${{ github.event.repository.description }}
